/* This file was generated with gen_C_code.m from fixed/cursive.jhf */

/* number of glyphs in font */
unsigned char cursive_cnt = 96;

/* Format: margin left, margin right, X, Y ... \0
< R> is pen-up, see original hershey font */
const char cursive [] PROGMEM="JZ\0"\
          "MWRFRT RRYQZR[SZRY\0"\
          "JZNFNM RVFVM\0"\
          "H]SBLb RYBRb RLOZO RKUYU\0"\
          "H\\PBP_ RTBT_ RYIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX\0"\
          "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT\0"\
          "E_\\O\\N[MZMYNXPVUTXRZP[L[JZIYHWHUISJRQNRMSKSIRGPFNGMIMKNNPQUXWZY[[[\\Z\\Y\0"\
          "PTRMRQ\0"\
          "KYVBTDRGPKOPOTPYR]T`Vb\0"\
          "KYNBPDRGTKUPUTTYR]P`Nb\0"\
          "JZRLRX RMOWU RWOMU\0"\
          "E_RIR[ RIR[R\0"\
          "NVSWRXQWRVSWSYQ[\0"\
          "E_IR[R\0"\
          "NVRVQWRXSWRV\0"\
          "G][BIb\0"\
          "H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF\0"\
          "H\\NJPISFS[\0"\
          "H\\LKLJMHNGPFTFVGWHXJXLWNUQK[Y[\0"\
          "H\\MFXFRNUNWOXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\UFKTZT RUFU[\0"\
          "H\\WFMFLOMNPMSMVNXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\XIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQLT\0"\
          "H\\YFO[ RKFYF\0"\
          "H\\PFMGLILKMMONSOVPXRYTYWXYWZT[P[MZLYKWKTLRNPQOUNWMXKXIWGTFPF\0"\
          "H\\XMWPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLX\0"\
          "NVROQPRQSPRO RRVQWRXSWRV\0"\
          "NVROQPRQSPRO RSWRXQWRVSWSYQ[\0"\
          "F^ZIJRZ[\0"\
          "E_IO[O RIU[U\0"\
          "F^JIZRJ[\0"\
          "I[LKLJMHNGPFTFVGWHXJXLWNVORQRT RRYQZR[SZRY\0"\
          "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV\0"\
          "G[G[IZLWOSSLVFV[UXSUQSNQLQKRKTLVNXQZT[Y[\0"\
          "F]SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFXFZG[I[KZMYNWOTP RSPTPWQXRYTYWXYWZU[R[PZOX\0"\
          "H\\TLTMUNWNYMZKZIYGWFTFQGOIMLLNKRKVLYMZO[Q[TZVXWV\0"\
          "G^TFRGQIPMOSNVMXKZI[G[FZFXGWIWKXMZP[S[VZXXZT[O[KZHYGWFTFRHRJSMUPWRZT\\U\0"\
          "H\\VJVKWLYLZKZIYGVFRFOGNINLONPOSPPPMQLRKTKWLYMZP[S[VZXXYV\0"\
          "H\\RLPLNKMINGQFTFXG[G]F RXGVNTTRXPZN[L[JZIXIVJULUNV RQPZP\0"\
          "G^G[IZMVPQQNRJRGQFPFOGNINLONQOUOXNYMZKZQYVXXVZS[O[LZJXIVIT\0"\
          "F^MMKLJJJIKGMFNFPGQIQKPONULYJ[H[GZGX RMRVOXN[L]J^H^G]F\\FZHXLVRUWUZV[W[YZZY\\V\0"\
          "IZWVUTSQROQLQIRGSFUFVGWIWLVQTVSXQZO[M[KZJXJVKUMUOV\0"\
          "JYT^R[PVOPOJPGRFTFUGVJVMURR[PaOdNfLgKfKdLaN^P\\SZWX\0"\
          "F^MMKLJJJIKGMFNFPGQIQKPONULYJ[H[GZGX R^I^G]F\\FZGXIVLTNROPO RROSQSXTZU[V[XZYY[V\0"\
          "I\\MRORSQVOXMYKYHXFVFUGTISNRSQVPXNZL[J[IZIXJWLWNXQZT[V[YZ[X\0"\
          "@aEMCLBJBICGEFFFHGIIIKHPGTE[ RGTJLLHMGOFPFRGSISKRPQTO[ RQTTLVHWGYFZF\\G]I]K\\PZWZZ[[\\[^Z_YaV\0"\
          "E]JMHLGJGIHGJFKFMGNINKMPLTJ[ RLTOLQHRGTFVFXGYIYKXPVWVZW[X[ZZ[Y]V\0"\
          "H]TFQGOIMLLNKRKVLYMZO[Q[TZVXXUYSZOZKYHXGVFTFRHRKSNUQWSZU\\V\0"\
          "F_SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFZF\\G]H^J^M]O\\PZQWQUPTO\0"\
          "H^ULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWSSWPYNZK[I[HZHXIWKWMXPZS[V[YZ[X\0"\
          "F_SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFYF[G\\H]J]M\\O[PYQVQSPTQUSUXVZX[ZZ[Y]V\0"\
          "H\\H[JZLXOTQQSMTJTGSFRFQGPIPKQMSOVQXSYUYWXYWZT[P[MZKXJVJT\0"\
          "H[RLPLNKMINGQFTFXG[G]F RXGVNTTRXPZN[L[JZIXIVJULUNV\0"\
          "E]JMHLGJGIHGJFKFMGNINKMOLRKVKXLZN[P[RZSYUUXMZF RXMWQVWVZW[X[ZZ[Y]V\0"\
          "F]KMILHJHIIGKFLFNGOIOKNOMRLVLYM[O[QZTWVTXPYMZIZGYFXFWGVIVKWNYP[Q\0"\
          "C_HMFLEJEIFGHFIFKGLILLK[ RUFK[ RUFS[ RaF_G\\JYNVTS[\0"\
          "F^NLLLKKKILGNFPFRGSISLQUQXRZT[V[XZYXYVXUVU R]I]G\\FZFXGVITLPUNXLZJ[H[GZGX\0"\
          "F]KMILHJHIIGKFLFNGOIOKNOMRLVLXMZN[P[RZTXVUWSYM R[FYMVWT]RbPfNgMfMdNaP^S[VY[V\0"\
          "H]ULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWTTWPZN[K[JZJXKWNWPXQYR[R^QaPcNfLgKfKdLaN^Q[TYZV\0"\
          "KYOBOb RPBPb ROBVB RObVb\0"\
          "KYKFY^\0"\
          "KYTBTb RUBUb RNBUB RNbUb\0"\
          "JZRDJR RRDZR\0"\
          "G[Gb[b\0"\
          "NVSKQMQORPSORNQO\0"\
          "L\\UUTSRRPRNSMTLVLXMZO[Q[SZTXVRUWUZV[W[YZZY\\V\0"\
          "M[MVOSRNSLTITGSFQGPIOMNTNZO[P[RZTXUUURVVWWYW[V\0"\
          "MXTTTSSRQROSNTMVMXNZP[S[VYXV\0"\
          "L\\UUTSRRPRNSMTLVLXMZO[Q[SZTXZF RVRUWUZV[W[YZZY\\V\0"\
          "NXOYQXRWSUSSRRQROSNUNXOZQ[S[UZVYXV\0"\
          "OWOVSQUNVLWIWGVFTGSIQQNZKaJdJfKgMfNcOZP[R[TZUYWV\0"\
          "L[UUTSRRPRNSMTLVLXMZO[Q[SZTY RVRTYPdOfMgLfLdMaP^S\\U[XY[V\0"\
          "M\\MVOSRNSLTITGSFQGPIOMNSM[ RM[NXOVQSSRURVSVUUXUZV[W[YZZY\\V\0"\
          "PWSMSNTNTMSM RPVRRPXPZQ[R[TZUYWV\0"\
          "PWSMSNTNTMSM RPVRRLdKfIgHfHdIaL^O\\Q[TYWV\0"\
          "M[MVOSRNSLTITGSFQGPIOMNSM[ RM[NXOVQSSRURVSVUTVQV RQVSWTZU[V[XZYY[V\0"\
          "OWOVQSTNULVIVGUFSGRIQMPTPZQ[R[TZUYWV\0"\
          "E^EVGSIRJSJTIXH[ RIXJVLSNRPRQSQTPXO[ RPXQVSSURWRXSXUWXWZX[Y[[Z\\Y^V\0"\
          "J\\JVLSNROSOTNXM[ RNXOVQSSRURVSVUUXUZV[W[YZZY\\V\0"\
          "LZRRPRNSMTLVLXMZO[Q[SZTYUWUUTSRRQSQURWTXWXYWZV\0"\
          "KZKVMSNQMUGg RMUNSPRRRTSUUUWTYSZQ[ RMZO[R[UZWYZV\0"\
          "L[UUTSRRPRNSMTLVLXMZO[Q[SZ RVRUUSZPaOdOfPgRfScS\\U[XY[V\0"\
          "MZMVOSPQPSSSTTTVSYSZT[U[WZXYZV\0"\
          "NYNVPSQQQSSVTXTZR[ RNZP[T[VZWYYV\0"\
          "OXOVQSSO RVFPXPZQ[S[UZVYXV RPNWN\0"\
          "L[LVNRLXLZM[O[QZSXUU RVRTXTZU[V[XZYY[V\0"\
          "L[LVNRMWMZN[O[RZTXUUUR RURVVWWYW[V\0"\
          "I^LRJTIWIYJ[L[NZPX RRRPXPZQ[S[UZWXXUXR RXRYVZW\\W^V\0"\
          "JZJVLSNRPRQSQZR[U[XYZV RWSVRTRSSOZN[L[KZ\0"\
          "L[LVNRLXLZM[O[QZSXUU RVRPdOfMgLfLdMaP^S\\U[XY[V\0"\
          "LZLVNSPRRRTTTVSXQZN[P\\Q^QaPdOfMgLfLdMaP^S\\WYZV\0"\
          "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb\0"\
          "NVRBRb\0"\
          "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb\0"\
          "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O\0"\
          "JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[\0"\
;
/* End of file gen_c_src/cursive.h */
