/* This file was generated with gen_C_code.m from fixed/futuram.jhf */

/* number of glyphs in font */
unsigned char futuram_cnt = 96;

/* Format: margin left, margin right, X, Y ... \0
< R> is pen-up, see original hershey font */
const char futuram [] PROGMEM="JZ\0"\
          "MXRFRTST RRFSFST RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY\0"\
          "I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM\0"\
          "H]SBLb RYBRb RLOZO RKUYU\0"\
          "I\\RBR_S_ RRBSBS_ RWIYIWGTFQFNGLILKMMNNVRWSXUXWWYTZQZOYNX RWIVHTGQGNHMIMKNMVQXSYUYWXYWZT[Q[NZLXNX RXXUZ\0"\
          "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT\0"\
          "F_[NZO[P\\O\\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\\Z\\Y RM[KZJXJUKSMQ RMKNMVXXZZ[\0"\
          "NWSFRGRM RSGRM RSFTGRM\0"\
          "KYVBTDRGPKOPOTPYR]T`Vb RTDRHQKPPPTQYR\\T`\0"\
          "KYNBPDRGTKUPUTTYR]P`Nb RPDRHSKTPTTSYR\\P`\0"\
          "JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO\0"\
          "F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R\0"\
          "MXTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^\0"\
          "E_IR[R\0"\
          "MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY\0"\
          "G^[BIbJb R[B\\BJb\0"\
          "H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF ROGMJLOLRMWOZ RNYQZSZVY RUZWWXRXOWJUG RVHSGQGNH\0"\
          "H\\NJPISFS[ RNJNKPJRHR[S[\0"\
          "H\\LKLJMHNGPFTFVGWHXJXLWNUQL[ RLKMKMJNHPGTGVHWJWLVNTQK[ RLZYZY[ RK[Y[\0"\
          "H\\MFXFQO RMFMGWG RWFPO RQNSNVOXQYTYUXXVZS[P[MZLYKWLW RPOSOVPXS RTOWQXTXUWXTZ RXVVYSZPZMYLW ROZLX\0"\
          "H\\UIU[V[ RVFV[ RVFKVZV RUILV RLUZUZV\0"\
          "H\\MFLO RNGMN RMFWFWG RNGWG RMNPMSMVNXPYSYUXXVZS[P[MZLYKWLW RLOMOONSNVOXR RTNWPXSXUWXTZ RXVVYSZPZMYLW ROZLX\0"\
          "H\\VGWIXIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQ RWHTGRGOH RPGNJMOMTNXQZ RMVOYRZSZVYXV RTZWXXUXTWQTO RXSVPSOROOPMS RQONQMT\0"\
          "H\\KFYFO[ RKFKGXG RXFN[O[\0"\
          "H\\PFMGLILKMMNNPOTPVQWRXTXWWYTZPZMYLWLTMRNQPPTOVNWMXKXIWGTFPF RNGMIMKNMPNTOVPXRYTYWXYWZT[P[MZLYKWKTLRNPPOTNVMWKWIVG RWHTGPGMH RLXOZ RUZXX\0"\
          "H\\WPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLXMXNZ RWMVPSR RWNUQRRQRNQLN RPRMPLMLLMIPG RLKNHQGRGUHWK RSGVIWMWRVWTZ RUYRZPZMY\0"\
          "MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY\0"\
          "MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^\0"\
          "F^ZIJRZ[\0"\
          "F_JM[M[N RJMJN[N RJU[U[V RJUJV[V\0"\
          "F^JIZRJ[\0"\
          "I\\LKLJMHNGQFTFWGXHYJYLXNWOUPRQ RLKMKMJNHQGTGWHXJXLWNUORP RMIPG RUGXI RXMTP RRPRTSTSP RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY\0"\
          "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV\0"\
          "H\\RFJ[ RRIK[J[ RRIY[Z[ RRFZ[ RMUWU RLVXV\0"\
          "H\\LFL[ RMGMZ RLFTFWGXHYJYMXOWPTQ RMGTGWHXJXMWOTP RMPTPWQXRYTYWXYWZT[L[ RMQTQWRXTXWWYTZMZ\0"\
          "H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV RZKYKXIWHUGQGOHMKLNLSMVOYQZUZWYXXYVZV\0"\
          "H]LFL[ RMGMZ RLFSFVGXIYKZNZSYVXXVZS[L[ RMGSGVHWIXKYNYSXVWXVYSZMZ\0"\
          "I\\MFM[ RNGNZ RMFYF RNGYGYF RNPTPTQ RNQTQ RNZYZY[ RM[Y[\0"\
          "I[MFM[ RNGN[M[ RMFYF RNGYGYF RNPTPTQ RNQTQ\0"\
          "H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZRUR RZKYKXIWHUGQGOHNIMKLNLSMVNXOYQZUZWYXXYVYSUSUR\0"\
          "G]KFK[ RKFLFL[K[ RYFXFX[Y[ RYFY[ RLPXP RLQXQ\0"\
          "NWRFR[S[ RRFSFS[\0"\
          "J[VFVVUYSZQZOYNVMV RVFWFWVVYUZS[Q[OZNYMV\0"\
          "H]LFL[M[ RLFMFM[ RZFYFMR RZFMS RPOY[Z[ RQOZ[\0"\
          "IZMFM[ RMFNFNZ RNZYZY[ RM[Y[\0"\
          "F^JFJ[ RKKK[J[ RKKR[ RJFRX RZFRX RYKR[ RYKY[Z[ RZFZ[\0"\
          "G]KFK[ RLIL[K[ RLIY[ RKFXX RXFXX RXFYFY[\0"\
          "G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG\0"\
          "H\\LFL[ RMGM[L[ RLFUFWGXHYJYMXOWPUQMQ RMGUGWHXJXMWOUPMP\0"\
          "G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG RSXX]Y] RSXTXY]\0"\
          "H\\LFL[ RMGM[L[ RLFTFWGXHYJYMXOWPTQMQ RMGTGWHXJXMWOTPMP RRQX[Y[ RSQY[\0"\
          "H\\YIWGTFPFMGKIKKLMMNOOTQVRWSXUXXWYTZPZNYMXKX RYIWIVHTGPGMHLILKMMONTPVQXSYUYXWZT[P[MZKX\0"\
          "J[RGR[ RSGS[R[ RLFYFYG RLFLGYG\0"\
          "G]KFKULXNZQ[S[VZXXYUYF RKFLFLUMXNYQZSZVYWXXUXFYF\0"\
          "H\\JFR[ RJFKFRX RZFYFRX RZFR[\0"\
          "E_GFM[ RGFHFMX RRFMX RRIM[ RRIW[ RRFWX R]F\\FWX R]FW[\0"\
          "H\\KFX[Y[ RKFLFY[ RYFXFK[ RYFL[K[\0"\
          "I\\KFRPR[S[ RKFLFSP RZFYFRP RZFSPS[\0"\
          "H\\XFK[ RYFL[ RKFYF RKFKGXG RLZYZY[ RK[Y[\0"\
          "KYOBOb RPBPb ROBVB RObVb\0"\
          "KYKFY^\0"\
          "KYTBTb RUBUb RNBUB RNbUb\0"\
          "G]JTROZT RJTRPZT\0"\
          "H\\Hb\\b\0"\
          "LXPFUL RPFOGUL\0"\
          "H\\WMW[X[ RWMXMX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX\0"\
          "H\\LFL[M[ RLFMFM[ RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX\0"\
          "I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX RXPWQVOTNQNOONPMSMUNXOYQZTZVYWWXX\0"\
          "H\\WFW[X[ RWFXFX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX\0"\
          "I[MTXTXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX RMSWSWQVOTNQNOONPMSMUNXOYQZTZVYWWXX\0"\
          "LZWFUFSGRJR[S[ RWFWGUGSH RTGSJS[ ROMVMVN ROMONVN\0"\
          "H\\XMWMW\\V_U`SaQaO`N_L_ RXMX\\W_UaSbPbNaL_ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX\0"\
          "H\\LFL[M[ RLFMFM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[\0"\
          "NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMR[S[ RRMSMS[\0"\
          "NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMRbSb RRMSMSb\0"\
          "H[LFL[M[ RLFMFM[ RXMWMMW RXMMX RPTV[X[ RQSX[\0"\
          "NWRFR[S[ RRFSFS[\0"\
          "CbGMG[H[ RGMHMH[ RHQKNMMPMRNSQS[ RHQKOMNONQORQR[S[ RSQVNXM[M]N^Q^[ RSQVOXNZN\\O]Q][^[\0"\
          "H\\LML[M[ RLMMMM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[\0"\
          "I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM RQNOONPMSMUNXOYQZTZVYWXXUXSWPVOTNQN\0"\
          "H\\LMLbMb RLMMMMb RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX\0"\
          "H\\WMWbXb RWMXMXb RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX\0"\
          "KYOMO[P[ ROMPMP[ RPSQPSNUMXM RPSQQSOUNXNXM\0"\
          "J[XPWNTMQMNNMPNRPSUUWV RVUWWWXVZ RWYTZQZNY ROZNXMX RXPWPVN RWOTNQNNO RONNPOR RNQPRUTWUXWXXWZT[Q[NZMX\0"\
          "MXRFR[S[ RRFSFS[ ROMVMVN ROMONVN\0"\
          "H\\LMLWMZO[R[TZWW RLMMMMWNYPZRZTYWW RWMW[X[ RWMXMX[\0"\
          "JZLMR[ RLMMMRY RXMWMRY RXMR[\0"\
          "F^IMN[ RIMJMNX RRMNX RRPN[ RRPV[ RRMVX R[MZMVX R[MV[\0"\
          "I[LMW[X[ RLMMMX[ RXMWML[ RXMM[L[\0"\
          "JZLMR[ RLMMMRY RXMWMRYNb RXMR[ObNb\0"\
          "I[VNL[ RXMNZ RLMXM RLMLNVN RNZXZX[ RL[X[\0"\
          "KYUBNRUb\0"\
          "NVRBRb\0"\
          "KYOBVROb\0"\
          "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O\0"\
          "JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[\0"\
;
/* End of file gen_c_src/futuram.h */
