/* This file was generated with gen_C_code.m from fixed/mathlow.jhf */

/* number of glyphs in font */
unsigned char mathlow_cnt = 96;

/* Format: margin left, margin right, X, Y ... \0
< R> is pen-up, see original hershey font */
const char mathlow [] PROGMEM="JZ\0"\
          "F^RJR[ RJRZR RJ[Z[\0"\
          "F^RJR[ RJJZJ RJRZR\0"\
          "G]KKYY RYKKY\0"\
          "PURQRRSRSQRQ\0"\
          "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT\0"\
          "F^ZFJMZT RJVZV RJ[Z[\0"\
          "F^JFZMJT RJVZV RJ[Z[\0"\
          "KYVBTDRGPKOPOTPYR]T`Vb RTDRHQKPPPTQYR\\T`\0"\
          "KYNBPDRGTKUPUTTYR]P`Nb RPDRHSKTPTTSYR\\P`\0"\
          "JZRLRX RMOWU RWOMU\0"\
          "E_RIR[ RIR[R\0"\
          "NVSWRXQWRVSWSYQ[\0"\
          "E_IR[R\0"\
          "NVRVQWRXSWRV\0"\
          "G][BIb\0"\
          "H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF\0"\
          "H\\NJPISFS[\0"\
          "H\\LKLJMHNGPFTFVGWHXJXLWNUQK[Y[\0"\
          "H\\MFXFRNUNWOXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\UFKTZT RUFU[\0"\
          "H\\WFMFLOMNPMSMVNXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\XIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQLT\0"\
          "H\\YFO[ RKFYF\0"\
          "H\\PFMGLILKMMONSOVPXRYTYWXYWZT[P[MZLYKWKTLRNPQOUNWMXKXIWGTFPF\0"\
          "H\\XMWPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLX\0"\
          "AcHBHb RIBIb R[B[b R\\B\\b RDB`B RDbMb RWb`b\0"\
          "BaGBQPFb RFBPP REBPQ REB\\B^I[B RGa\\a RFb\\b^[[b\0"\
          "F^ZIJRZ[\0"\
          "E_IO[O RIU[U\0"\
          "F^JIZRJ[\0"\
          "E_YIK[ RIO[O RIU[U\0"\
          "E_IM[M RIR[R RIW[W\0"\
          "I\\XMX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "H[LFL[ RLPNNPMSMUNWPXSXUWXUZS[P[NZLX\0"\
          "I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I\\XFX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I[LSXSXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "MYWFUFSGRJR[ ROMVM\0"\
          "I\\XMX]W`VaTbQbOa RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I\\MFM[ RMQPNRMUMWNXQX[\0"\
          "NVQFRGSFREQF RRMR[\0"\
          "MWRFSGTFSERF RSMS^RaPbNb\0"\
          "IZMFM[ RWMMW RQSX[\0"\
          "NVRFR[\0"\
          "CaGMG[ RGQJNLMOMQNRQR[ RRQUNWMZM\\N]Q][\0"\
          "I\\MMM[ RMQPNRMUMWNXQX[\0"\
          "I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM\0"\
          "H[LMLb RLPNNPMSMUNWPXSXUWXUZS[P[NZLX\0"\
          "I\\XMXb RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "KXOMO[ ROSPPRNTMWM\0"\
          "J[XPWNTMQMNNMPNRPSUTWUXWXXWZT[Q[NZMX\0"\
          "MYRFRWSZU[W[ ROMVM\0"\
          "I\\MMMWNZP[S[UZXW RXMX[\0"\
          "JZLMR[ RXMR[\0"\
          "G]JMN[ RRMN[ RRMV[ RZMV[\0"\
          "J[MMX[ RXMM[\0"\
          "JZLMR[ RXMR[P_NaLbKb\0"\
          "J[XMM[ RMMXM RM[X[\0"\
          "KYOBOb RPBPb ROBVB RObVb\0"\
          "KYKFY^\0"\
          "KYTBTb RUBUb RNBUB RNbUb\0"\
          "F_[WYWWVUTRPQOONMNKOJQJSKUMVOVQURTUPWNYM[M\0"\
          "F_\\S[UYVWVUUTTQPPONNLNJOIQISJULVNVPUQTTPUOWNYN[O\\Q\\S\0"\
          "KYQFOGNINKOMQNSNUMVKVIUGSFQF\0"\
          "H\\PBP_ RTBT_ RYIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX\0"\
          "E[HMLMRY RKMR[ R[BR[\0"\
          "AbDMIMRY RHNR[ Rb:R[\0"\
          "F^ZJSJOKMLKNJQJSKVMXOYSZZZ\0"\
          "F^JJJQKULWNYQZSZVYXWYUZQZJ\0"\
          "F^JJQJUKWLYNZQZSYVWXUYQZJZ\0"\
          "F^JZJSKOLMNKQJSJVKXMYOZSZZ\0"\
          "F^ZJSJOKMLKNJQJSKVMXOYSZZZ RJRVR\0"\
          "E_XP[RXT RUMZRUW RIRZR\0"\
          "JZPLRITL RMORJWO RRJR[\0"\
          "E_LPIRLT ROMJROW RJR[R\0"\
          "JZPXR[TX RMURZWU RRIRZ\0"\
          "I\\XRWOVNTMRMONMQLTLWMYNZP[R[UZWXXUYPYKXHWGUFRFPGOHOIPIPH RRMPNNQMTMXNZ RR[TZVXWUXPXKWHUF\0"\
          "H\\JFR[ RKFRY RZFR[ RJFZF RKGYG\0"\
          "AbDMIMRY RHNR[ Rb:R[\0"\
          "F^[CZD[E\\D\\C[BYBWCUETGSJRNPZO^N` RVDUFTJRVQZP]O_MaKbIbHaH`I_J`Ia\0"\
          "Ca].\\.[/[0\\1]1^0^.],[+Y+W,U.T0S3R:QJQjPsOv R\\/\\0]0]/\\/ RR:Rj RU.T1S:SZRjQqPtOvMxKyIyGxFvFtGsHsItIuHvGv RGtGuHuHtGt\0"\
          "I[X+U1R8P=OANFMNMVN^OcPgRlUsXy RU1S6Q<P@OFNNNVO^PdQhSnUs\0"\
          "I[L+O1R8T=UAVFWNWVV^UcTgRlOsLy RO1Q6S<T@UFVNVVU^TdShQnOs\0"\
          "I[M+MRMy RN+NRNy RM+X+ RMyXy\0"\
          "I[V+VRVy RW+WRWy RL+W+ RLyWy\0"\
          "I\\XFX[ RKFXF RPPXP RK[X[\0"\
          "H\\KILKXWYYY[ RLLXX RKIKKLMXYY[ RPPLTKVKXLZK[ RKVMZ RLTLVMXMZK[ RSSXN RVIVLWNYNYLWKVI RVIWLYN\0"\
          "E_RIQJRKSJRI RIR[R RRYQZR[SZRY\0"\
          "KYOBOb RUBUb\0"\
          "F^RBR[ RI[[[\0"\
          "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb\0"\
          "F^[BI[[[\0"\
          "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb\0"\
          "E_RIQJRKSJRI RIYHZI[JZIY R[YZZ[[\\Z[Y\0"\
          "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O\0"\
;
/* End of file gen_c_src/mathlow.h */
