/* This file was generated with gen_C_code.m from fixed/meteorology.jhf */

/* number of glyphs in font */
unsigned char meteorology_cnt = 96;

/* Format: margin left, margin right, X, Y ... \0
< R> is pen-up, see original hershey font */
const char meteorology [] PROGMEM="JZ\0"\
          "PSSRRSQSPRPQQPRPSQSSRUQV RQQQRRRRQQQ\0"\
          "PTQPPQPSQTSTTSTQSPQP RRQQRRSSRRQ\0"\
          "NVPOTU RTOPU RNRVR\0"\
          "MWRKQMOPMR RRKSMUPWR RRMOQ RRMUQ RROPQ RROTQ RQQSQ RMRWR\0"\
          "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT\0"\
          "MWMRMQNOONQMSMUNVOWQWR RPNTN ROOUO RNPVP RNQVQ RMRWR\0"\
          "LRLFLRRRLF RLIPQ RLLOR RLOMQ\0"\
          "MWRKQMOPMR RRKSMUPWR\0"\
          "MWWRWQVOUNSMQMONNOMQMR\0"\
          "JZRLRX RMOWU RWOMU\0"\
          "G]]R]P\\MZJWHTGPGMHJJHMGPGR\0"\
          "NVSWRXQWRVSWSYQ[\0"\
          "E_IR[R\0"\
          "NVRVQWRXSWRV\0"\
          "G][BIb\0"\
          "H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF\0"\
          "H\\NJPISFS[\0"\
          "H\\LKLJMHNGPFTFVGWHXJXLWNUQK[Y[\0"\
          "H\\MFXFRNUNWOXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\UFKTZT RUFU[\0"\
          "H\\WFMFLOMNPMSMVNXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\XIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQLT\0"\
          "H\\YFO[ RKFYF\0"\
          "H\\PFMGLILKMMONSOVPXRYTYWXYWZT[P[MZLYKWKTLRNPQOUNWMXKXIWGTFPF\0"\
          "H\\XMWPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLX\0"\
          "MWMRMSNUOVQWSWUVVUWSWR\0"\
          "LXLPNRQSSSVRXP\0"\
          "RURUTTURTPRO\0"\
          "RVRRUPVNVLUKTK\0"\
          "NRRROPNNNLOKPK\0"\
          "I[MJNKMLLKLJMHNGPFSFVGWHXJXLWNVORQRT RSFUGVHWJWLVNTP RRYQZR[SZRY\0"\
          "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV\0"\
          "I[RFJ[ RRFZ[ RMTWT\0"\
          "G\\KFK[ RKFTFWGXHYJYLXNWOTP RKPTPWQXRYTYWXYWZT[K[\0"\
          "H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV\0"\
          "G\\KFK[ RKFRFUGWIXKYNYSXVWXUZR[K[\0"\
          "H[LFL[ RLFYF RLPTP RL[Y[\0"\
          "HZLFL[ RLFYF RLPTP\0"\
          "H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZS RUSZS\0"\
          "G]KFK[ RYFY[ RKPYP\0"\
          "NVRFR[\0"\
          "JZVFVVUYTZR[P[NZMYLVLT\0"\
          "G\\KFK[ RYFKT RPOY[\0"\
          "HYLFL[ RL[X[\0"\
          "F^JFJ[ RJFR[ RZFR[ RZFZ[\0"\
          "G]KFK[ RKFY[ RYFY[\0"\
          "G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF\0"\
          "G\\KFK[ RKFTFWGXHYJYMXOWPTQKQ\0"\
          "G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RSWY]\0"\
          "G\\KFK[ RKFTFWGXHYJYLXNWOTPKP RRPY[\0"\
          "H\\YIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX\0"\
          "JZRFR[ RKFYF\0"\
          "G]KFKULXNZQ[S[VZXXYUYF\0"\
          "I[JFR[ RZFR[\0"\
          "F^HFM[ RRFM[ RRFW[ R\\FW[\0"\
          "H\\KFY[ RYFK[\0"\
          "I[JFRPR[ RZFRP\0"\
          "H\\YFK[ RKFYF RK[Y[\0"\
          "KYOBOb RPBPb ROBVB RObVb\0"\
          "KYKFY^\0"\
          "KYTBTb RUBUb RNBUB RNbUb\0"\
          "H\\YIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX\0"\
          "G]RRTUUVWWYW[V\\U]S]Q\\O[NYMWMUNTOPUOVMWKWIVHUGSGQHOINKMMMONPORR\0"\
          "G]IWHVGTGQHOINKMMMONPOTUUVWWYW[V\\U]S]P\\N[M\0"\
          "I\\XMX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "H[LFL[ RLPNNPMSMUNWPXSXUWXUZS[P[NZLX\0"\
          "I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I\\XFX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I[LSXSXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "MYWFUFSGRJR[ ROMVM\0"\
          "I\\XMX]W`VaTbQbOa RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I\\MFM[ RMQPNRMUMWNXQX[\0"\
          "NVQFRGSFREQF RRMR[\0"\
          "MWRFSGTFSERF RSMS^RaPbNb\0"\
          "IZMFM[ RWMMW RQSX[\0"\
          "NVRFR[\0"\
          "CaGMG[ RGQJNLMOMQNRQR[ RRQUNWMZM\\N]Q][\0"\
          "I\\MMM[ RMQPNRMUMWNXQX[\0"\
          "I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM\0"\
          "H[LMLb RLPNNPMSMUNWPXSXUWXUZS[P[NZLX\0"\
          "I\\XMXb RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "KXOMO[ ROSPPRNTMWM\0"\
          "J[XPWNTMQMNNMPNRPSUTWUXWXXWZT[Q[NZMX\0"\
          "MYRFRWSZU[W[ ROMVM\0"\
          "I\\MMMWNZP[S[UZXW RXMX[\0"\
          "JZLMR[ RXMR[\0"\
          "G]JMN[ RRMN[ RRMV[ RZMV[\0"\
          "J[MMX[ RXMM[\0"\
          "JZLMR[ RXMR[P_NaLbKb\0"\
          "J[XMM[ RMMXM RM[X[\0"\
          "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb\0"\
          "H\\KFK[ RHF[FQP[Z RZV[Y\\[ RZVZY RWYZY RWYZZ\\[\0"\
          "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb\0"\
          "KYUARBPCNELHKLKRLUNWQXSXVWXUYR RKPLMNKQJSJVKXMYPYVXZV]T_R`Oa\0"\
          "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O\0"\
;
/* End of file gen_c_src/meteorology.h */
