/* This file was generated with gen_C_code.m from fixed/rowmans.jhf */

/* number of glyphs in font */
unsigned char rowmans_cnt = 96;

/* Format: margin left, margin right, X, Y ... \0
< R> is pen-up, see original hershey font */
const char rowmans [] PROGMEM="JZ\0"\
          "MWRFRT RRYQZR[SZRY\0"\
          "JZNFNM RVFVM\0"\
          "H]SBLb RYBRb RLOZO RKUYU\0"\
          "H\\PBP_ RTBT_ RYIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX\0"\
          "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT\0"\
          "E_\\O\\N[MZMYNXPVUTXRZP[L[JZIYHWHUISJRQNRMSKSIRGPFNGMIMKNNPQUXWZY[[[\\Z\\Y\0"\
          "MWRHQGRFSGSIRKQL\0"\
          "KYVBTDRGPKOPOTPYR]T`Vb\0"\
          "KYNBPDRGTKUPUTTYR]P`Nb\0"\
          "JZRFRR RMIWO RWIMO\0"\
          "E_RIR[ RIR[R\0"\
          "MWSZR[QZRYSZS\\R^Q_\0"\
          "E_IR[R\0"\
          "MWRYQZR[SZRY\0"\
          "G][BIb\0"\
          "H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF\0"\
          "H\\NJPISFS[\0"\
          "H\\LKLJMHNGPFTFVGWHXJXLWNUQK[Y[\0"\
          "H\\MFXFRNUNWOXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\UFKTZT RUFU[\0"\
          "H\\WFMFLOMNPMSMVNXPYSYUXXVZS[P[MZLYKW\0"\
          "H\\XIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQLT\0"\
          "H\\YFO[ RKFYF\0"\
          "H\\PFMGLILKMMONSOVPXRYTYWXYWZT[P[MZLYKWKTLRNPQOUNWMXKXIWGTFPF\0"\
          "H\\XMWPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLX\0"\
          "MWRMQNROSNRM RRYQZR[SZRY\0"\
          "MWRMQNROSNRM RSZR[QZRYSZS\\R^Q_\0"\
          "F^ZIJRZ[\0"\
          "E_IO[O RIU[U\0"\
          "F^JIZRJ[\0"\
          "I[LKLJMHNGPFTFVGWHXJXLWNVORQRT RRYQZR[SZRY\0"\
          "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV\0"\
          "I[RFJ[ RRFZ[ RMTWT\0"\
          "G\\KFK[ RKFTFWGXHYJYLXNWOTP RKPTPWQXRYTYWXYWZT[K[\0"\
          "H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV\0"\
          "G\\KFK[ RKFRFUGWIXKYNYSXVWXUZR[K[\0"\
          "H[LFL[ RLFYF RLPTP RL[Y[\0"\
          "HZLFL[ RLFYF RLPTP\0"\
          "H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZS RUSZS\0"\
          "G]KFK[ RYFY[ RKPYP\0"\
          "NVRFR[\0"\
          "JZVFVVUYTZR[P[NZMYLVLT\0"\
          "G\\KFK[ RYFKT RPOY[\0"\
          "HYLFL[ RL[X[\0"\
          "F^JFJ[ RJFR[ RZFR[ RZFZ[\0"\
          "G]KFK[ RKFY[ RYFY[\0"\
          "G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF\0"\
          "G\\KFK[ RKFTFWGXHYJYMXOWPTQKQ\0"\
          "G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RSWY]\0"\
          "G\\KFK[ RKFTFWGXHYJYLXNWOTPKP RRPY[\0"\
          "H\\YIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX\0"\
          "JZRFR[ RKFYF\0"\
          "G]KFKULXNZQ[S[VZXXYUYF\0"\
          "I[JFR[ RZFR[\0"\
          "F^HFM[ RRFM[ RRFW[ R\\FW[\0"\
          "H\\KFY[ RYFK[\0"\
          "I[JFRPR[ RZFRP\0"\
          "H\\YFK[ RKFYF RK[Y[\0"\
          "KYOBOb RPBPb ROBVB RObVb\0"\
          "KYKFY^\0"\
          "KYTBTb RUBUb RNBUB RNbUb\0"\
          "JZPLRITL RMORJWO RRJR[\0"\
          "JZJ]Z]\0"\
          "MWSFRGQIQKRLSKRJ\0"\
          "I\\XMX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "H[LFL[ RLPNNPMSMUNWPXSXUWXUZS[P[NZLX\0"\
          "I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I\\XFX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I[LSXSXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "MYWFUFSGRJR[ ROMVM\0"\
          "I\\XMX]W`VaTbQbOa RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "I\\MFM[ RMQPNRMUMWNXQX[\0"\
          "NVQFRGSFREQF RRMR[\0"\
          "MWRFSGTFSERF RSMS^RaPbNb\0"\
          "IZMFM[ RWMMW RQSX[\0"\
          "NVRFR[\0"\
          "CaGMG[ RGQJNLMOMQNRQR[ RRQUNWMZM\\N]Q][\0"\
          "I\\MMM[ RMQPNRMUMWNXQX[\0"\
          "I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM\0"\
          "H[LMLb RLPNNPMSMUNWPXSXUWXUZS[P[NZLX\0"\
          "I\\XMXb RXPVNTMQMONMPLSLUMXOZQ[T[VZXX\0"\
          "KXOMO[ ROSPPRNTMWM\0"\
          "J[XPWNTMQMNNMPNRPSUTWUXWXXWZT[Q[NZMX\0"\
          "MYRFRWSZU[W[ ROMVM\0"\
          "I\\MMMWNZP[S[UZXW RXMX[\0"\
          "JZLMR[ RXMR[\0"\
          "G]JMN[ RRMN[ RRMV[ RZMV[\0"\
          "J[MMX[ RXMM[\0"\
          "JZLMR[ RXMR[P_NaLbKb\0"\
          "J[XMM[ RMMXM RM[X[\0"\
          "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb\0"\
          "NVRBRb\0"\
          "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb\0"\
          "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O\0"\
          "KYQFOGNINKOMQNSNUMVKVIUGSFQF\0"\
;
/* End of file gen_c_src/rowmans.h */
