/* This file was generated with gen_C_code.m from fixed/symbolic.jhf */

/* number of glyphs in font */
unsigned char symbolic_cnt = 96;

/* Format: margin left, margin right, X, Y ... \0
< R> is pen-up, see original hershey font */
const char symbolic [] PROGMEM="JZ\0"\
          "D`DR`R\0"\
          "D`D``D\0"\
          "RRR>Rf\0"\
          "D`DD``\0"\
          "D`DR`R\0"\
          "F^FY^K\0"\
          "KYK^YF\0"\
          "RRRDR`\0"\
          "KYKFY^\0"\
          "F^FK^Y\0"\
          "KYKRYR\0"\
          "MWMWWM\0"\
          "RRRKRY\0"\
          "MWMMWW\0"\
          "GRRGPGMHJJHMGPGR\0"\
          "GRGRGTHWJZM\\P]R]\0"\
          "R]R]T]W\\ZZ\\W]T]R\0"\
          "R]]R]P\\MZJWHTGRG\0"\
          "D`DOGQKSPTTTYS]Q`O\0"\
          "PUUDSGQKPPPTQYS]U`\0"\
          "OTODQGSKTPTTSYQ]O`\0"\
          "D`DUGSKQPPTPYQ]S`U\0"\
          "KYRJYNKVRZ\0"\
          "JZJRNKVYZR\0"\
          "KYKVKNYVYN\0"\
          "JZLXJPZTXL\0"\
          "JZJ]L]O\\Q[TXUVVSVOULTJSIQIPJOLNONSOVPXS[U\\X]Z]\0"\
          "I]]Z]X\\U[SXPVOSNONLOJPIQISJTLUOVSVVUXT[Q\\O]L]J\0"\
          "JZZGXGUHSIPLONNQNUOXPZQ[S[TZUXVUVQUNTLQIOHLGJG\0"\
          "G[GJGLHOIQLTNUQVUVXUZT[S[QZPXOUNQNNOLPISHUGXGZ\0"\
          "E[EPFRHTJUMVQVUUXSZP[NZLWLSMQNNPLSKVKYL\\M^\0"\
          "EYETHVKWPWSVVTXQYNYLXKVKSLPNNQMTMYN\\P_\0"\
          "OUQOOQOSQUSUUSUQSOQO RQPPQPSQTSTTSTQSPQP RRQQRRSSRRQ\0"\
          "RWRMSMUNVOWQWSVUUVSWRW\0"\
          "D`DRJR RORUR RZR`R\0"\
          "D`DUDO`O`U\0"\
          "JZRDJR RRDZR\0"\
          "D`DR`R RJYZY RP`T`\0"\
          "D`DR`R RDRRb R`RRb\0"\
          "KYQKNLLNKQKSLVNXQYSYVXXVYSYQXNVLSKQK\0"\
          "LXLLLXXXXLLL\0"\
          "KYRJKVYVRJ\0"\
          "LXRHLRR\\XRRH\0"\
          "JZRIPOJOOSMYRUWYUSZOTORI\0"\
          "KYRKRY RKRYR\0"\
          "MWMMWW RWMMW\0"\
          "MWRLRX RMOWU RWOMU\0"\
          "NVQNOONQNSOUQVSVUUVSVQUOSNQN ROQOS RPPPT RQOQU RRORU RSOSU RTPTT RUQUS\0"\
          "NVNNNVVVVNNN ROOOU RPOPU RQOQU RRORU RSOSU RTOTU RUOUU\0"\
          "MWRLMUWURL RROOT RROUT RRRQT RRRST\0"\
          "LULRUWUMLR RORTU RORTO RRRTS RRRTQ\0"\
          "MWRXWOMORX RRUUP RRUOP RRRSP RRRQP\0"\
          "OXXROMOWXR RURPO RURPU RRRPQ RRRPS\0"\
          "RYRKRY RRKYNRQ RSMVNSO\0"\
          "I[RGRV RMJWP RWJMP RIVL\\ R[VX\\ RIV[V RL\\X\\\0"\
          "MWRLRX ROOUO RMUOWQXSXUWWU\0"\
          "LXRLRX RLQMOWOXQ RPWTW\0"\
          "KYMNWX RWNMX ROLLOKQ RULXOYQ\0"\
          "I[NII[ RVI[[ RMM[[ RWMI[ RNIVI RMMWM\0"\
          "KYKFY^\0"\
          "G[MJSV RKPSL RG\\[\\[RG\\\0"\
          "LXPLPPLPLTPTPXTXTTXTXPTPTLPL\0"\
          "KYYPXNVLSKQKNLLNKQKSLVNXQYSYVXXVYT RYPWNUMSMQNPOOQOSPUQVSWUWWVYT\0"\
          "KYRJKVYVRJ RRZYNKNRZ\0"\
          "G]PIPGQFSFTGTI RGZHXJVKTLPLKMJOIUIWJXKXPYTZV\\X]Z RGZ]Z RQZP[Q\\S\\T[SZ\0"\
          "JZRMRS RRSQ\\ RRSS\\ RQ\\S\\ RRMQJPHNG RQJNG RRMSJTHVG RSJVG RRMNKLKJM RPLLLJM RRMVKXKZM RTLXLZM RRMPNOOOR RRMPOOR RRMTNUOUR RRMTOUR\0"\
          "JZRIRK RRNRP RRSRU RRYQ\\ RRYS\\ RQ\\S\\ RRGQIPJ RRGSITJ RPJRITJ RRKPNNOMN RRKTNVOWN RNOPORNTOVO RRPPSNTLTKRKSLT RRPTSVTXTYRYSXT RNTPTRSTTVT RRUPXOYMZLZKYJWJYLZ RRUTXUYWZXZYYZWZYXZ RMZOZRYUZWZ\0"\
          "JZRYQ\\ RRYS\\ RQ\\S\\ RRYUZXZZXZUYTWTYRZOYMWLUMVJUHSGQGOHNJOMMLKMJOKRMTKTJUJXLZOZRY\0"\
          "JZRYQ\\ RRYS\\ RQ\\S\\ RRYVXVVXUXRZQZLYIXHVHTGPGNHLHKIJLJQLRLUNVNXRY\0"\
          "I[IPKR RLKNP RRGRO RXKVP R[PYR\0"\
          "G]IIJKKOKUJYI[ R[IZKYOYUZY[[ RIIKJOKUKYJ[I RI[KZOYUYYZ[[\0"\
          "F^RRR[Q\\ RRVQ\\ RRIQHOHNINKONRR RRISHUHVIVKUNRR RRRNOLNJNIOIQJR RRRVOXNZN[O[QZR RRRNULVJVIUISJR RRRVUXVZV[U[SZR\0"\
          "JZUITJUKVJVIUGSFQFOGNINKOMQOVR ROMTPVRWTWVVXTZ RPNNPMRMTNVPXU[ RNVSYU[V]V_UaSbQbOaN_N^O]P^O_\0"\
          "JZRFQHRJSHRF RRFRb RRQQTRbSTRQ RLMNNPMNLLM RLMXM RTMVNXMVLTM\0"\
          "JZRFQHRJSHRF RRFRT RRPQRSVRXQVSRRP RRTRb RR^Q`RbS`R^ RLMNNPMNLLM RLMXM RTMVNXMVLTM RL[N\\P[NZL[ RL[X[ RT[V\\X[VZT[\0"\
          "E_RIQJRKSJRI RIYHZI[JZIY R[YZZ[[\\Z[Y\0"\
          "F^RHNLKPJSJUKWMXOXQWRU RRHVLYPZSZUYWWXUXSWRU RRUQYP\\ RRUSYT\\ RP\\T\\\0"\
          "F^RNQKPINHMHKIJKJOKRLTNWR\\ RRNSKTIVHWHYIZKZOYRXTVWR\\\0"\
          "F^RGPJLOIR RRGTJXO[R RIRLUPZR] R[RXUTZR]\0"\
          "F^RTTWVXXXZW[U[SZQXPVPSQ RSQUOVMVKUISHQHOINKNMOOQQ RQQNPLPJQISIUJWLXNXPWRT RRTQYP\\ RRTSYT\\ RP\\T\\\0"\
          "I[V+S-Q/P1O4O8P<TDUGUJTMRP RS-Q0P4P8Q;UCVGVJUMRPNRRTUWVZV]UaQiPlPpQtSw RRTTWUZU]T`PhOlOpPsQuSwVy\0"\
          "I[N+Q-S/T1U4U8T<PDOGOJPMRP RQ-S0T4T8S;OCNGNJOMRPVRRTOWNZN]OaSiTlTpStQw RRTPWOZO]P`ThUlUpTsSuQwNy\0"\
          "I[V.S1Q4O8N=NCOIPMSXT\\UbUgTlSoQs RS1Q5P8O=OBPHQLTWU[VaVgUlSpQsNv\0"\
          "I[N.Q1S4U8V=VCUITMQXP\\ObOgPlQoSs RQ1S5T8U=UBTHSLPWO[NaNgOlQpSsVv\0"\
          "7Z:RARRo R@RQo R?RRr RZ\"VJRr\0"\
          "I[TMVNXPXOWNTMQMNNMOLQLSMUOWSZ RQMONNOMQMSNUSZT\\T^S_Q_\0"\
          "G]LMKNJPJRKUOYP[ RJRKTOXP[P]O`MbLbKaJ_J\\KXMTOQRNTMVMYNZPZTYXWZU[T[SZSXTWUXTY RVMXNYPYTXXWZ\0"\
          "E_YGXHYIZHYGWFTFQGOINKMNLRJ[I_Ha RTFRGPIOKNNLWK[J^I`HaFbDbCaC`D_E`Da R_G^H_I`H`G_F]F[GZHYJXMU[T_Sa R]F[HZJYNWWV[U^T`SaQbObNaN`O_P`Oa RIM^M\0"\
          "F^[GZH[I\\H[GXFUFRGPIOKNNMRK[J_Ia RUFSGQIPKONMWL[K^J`IaGbEbDaD`E_F`Ea RYMWTVXVZW[Z[\\Y]W RZMXTWXWZX[ RJMZM\0"\
          "F^YGXHYIZHZGXF R\\FUFRGPIOKNNMRK[J_Ia RUFSGQIPKONMWL[K^J`IaGbEbDaD`E_F`Ea R[FWTVXVZW[Z[\\Y]W R\\FXTWXWZX[ RJMYM\0"\
          "@cTGSHTIUHTGRFOFLGJIIKHNGRE[D_Ca ROFMGKIJKINGWF[E^D`CaAb?b>a>`?_@`?a R`G_H`IaH`G]FZFWGUITKSNRRP[O_Na RZFXGVIUKTNRWQ[P^O`NaLbJbIaI`J_K`Ja R^M\\T[X[Z\\[_[aYbW R_M]T\\X\\Z][ RDM_M\0"\
          "@cTGSHTIUHTGRFOFLGJIIKHNGRE[D_Ca ROFMGKIJKINGWF[E^D`CaAb?b>a>`?_@`?a R^G]H^I_H_G]F RaFZFWGUITKSNRRP[O_Na RZFXGVIUKTNRWQ[P^O`NaLbJbIaI`J_K`Ja R`F\\T[X[Z\\[_[aYbW RaF]T\\X\\Z][ RDM^M\0"\
          "LYMQNOPMSMTNTQRWRZS[ RRMSNSQQWQZR[U[WYXW\0"\
          "LXRLNWXPLPVWRL RRRRL RRRLP RRRNW RRRVW RRRXP\0"\
          "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O\0"\
;
/* End of file gen_c_src/symbolic.h */
